src/middleware/authCheck.js, src/routes/auth.js, src/routes/client.js, src/routes/data.js, src/routes/news.js, src/routes/ticket.js, src/routes/time.js
The current API routes do not check who is making calls on /auth. This pull request addressed some of the known issues by making sure the calls are coming from an account with the 'admin' role.
Thes routes are:
/getAllusers
/resetPassword/:id
/getById
/edit
/delete/:Id
=> Add Authorization Checks

client/src/components/newsletter/Active.js, client/src/components/newsletter/ViewNewsletter.js, client/src/pages/Admin.js
Admin dash side nav on select dark grey background
announcements larger modal
=> Fixes and updates

client/src/components/ticket/Create.js, prisma/migrations/20210423234406_/migration.sql, prisma/schema.prisma, prisma/seed.js
=> add unknown client and user to seed | schema: add unique atribute to client email

pages/api/auth/[...nextauth].js, pages/auth/error.js
Added error message on error page
Changed focus rings to green
=> Error Page

components/UserProfile/index.js, i18n.js, locales/de/peppermint.json, locales/en/peppermint.json, pages/api/auth/[...nextauth].js, pages/api/v1/users/profile/edit.js, pages/index.js
You've been faster ;)  Hope it's ok this way.
Thanks a ton.
=> Pettier language switching, editable User-Profile

README.md, pages/history.js, pages/ticket/index.js
Fixed some minor errors in the example config. This is now the same config shown in the docs.
On the tables in the Tickets and History pages the value of client.name and name had been mixed up causing them to be shown in the wrong column/header.
=> Minor bug fix and README updated

components/CreateClientModal/index.js, components/CreateTicketModal/index.js, tailwind.config.js
Added a rudimental input validation on the frontend, it will check so that all fields when creating a client and a ticket has a value.
=> Input validation

apps/docs/pages/_meta.json, apps/docs/pages/docker.mdx, apps/docs/pages/index.mdx, apps/site/pages/index.tsx
Updates:
- Live Site: I corrected grammar issues on the website, revised the wording of the landing page, and added a website logo featuring a cup of tea as the tab icon. I also updated the copyright notice at the bottom to 2024. Additionally, I updated the front-page text to include more professional language. I corrected errors in the review section, where Network Chuck was mistakenly labeled as DBTech, along with many other edits in wording and grammar.
- Docs: Corrected grammatical errors and refined the language to incorporate a more professional tone.
- Sidebar: Changed font size and fixed the sidebar.
- Docker Docs: Fixed wording and attempted to bold some important info.
=> Updates to live Site & Docs

apps/site/pages/index.tsx
The version number at the top of the pages was updated.
=> Update Version #

apps/site/pages/index.tsx
=> Updating front page

apps/api/src/controllers/auth.ts, apps/api/src/controllers/users.ts, apps/client/components/ResetPassword/index.js, apps/client/layouts/newLayout.tsx, apps/client/pages/new.tsx, apps/client/pages/ticket/[id].tsx
Move ticket title to top of screen
=> fix: ticket title placement

apps/api/src/lib/imap.ts, apps/client/layouts/newLayout.tsx
Fixes two issues with imap ingest
- remove unused func causing ingest failure
- add null check to html import
=> fix: imap error

apps/api/src/controllers/auth.ts, apps/client/components/UpdateUserModal/index.tsx
=> fixes#307 require atleast one admin

apps/client/pages/admin/email-queues/index.js
=> FIX Typo in Admin Settings > Email Queues #309

apps/api/src/lib/nodemailer/ticket/status.ts
=> Use Number field instead of id field

apps/client/locales/he/peppermint.json
add more translations to hebrew
=> add more translations

apps/client/pages/admin/email-queues/new.js
The placeholders in the email queue page are all just set to "Enter first name..." for all fields. Wanted to update them to show what the field is actually looking for.
=> Change placeholders

apps/docs/pages/reverse-proxy.mdx
Commands are pulled from Certbot.eff.org.
=> Add instructions for installing and using Certbot

README.md
should be all good just a one liner to the README.md 
any inquiries or edits contact me via discord cooperdactor
Cheers Cooper
=> Update README.md to add spearmint 

apps/docs/package.json
Site broken cause the packages weren't updated. This should fix the problem.
=> chore: package updates

apps/api/src/lib/services/imap.service.ts
Email replies not saving as comments now fixed
=> fix: investigate email comments
